[package]
name = "speedy-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
swc_plugin = "=0.88.2"
serde_json = "*"
serde = "*"
speedy-transform = { path = "../crates/speedy-transform" }