name: Lint

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy
          target: wasm32-wasi

      - name: Install pnpm
        run: npm install -g pnpm@6

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-lint-node@14-${{ hashFiles('pnpm-lock.yaml') }}

      - name: 'Install dependencies'
        run: pnpm install --no-frozen-lockfile --registry https://registry.npmjs.org

      - name: ESLint
        run: pnpm lint

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy napi
        run: cargo clippy --verbose --workspace --exclude speedy-wasm -- --deny warnings

      # now skip, when use target wasm32-wasi, there are some problem using clippy
      # error: couldn't find crate `swc_atoms` with expected target triple wasm32-wasi
      # - name: Clippy wasm
      #   run: cargo clippy --verbose --package speedy-wasm -- --target wasm32-wasi
