

name: Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request: null

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name: Cargo test speedy-napi
        run: cargo test --workspace --exclude speedy-wasm
      
      - name: Cargo test speedy-wasm
        run: cargo test --package speedy-wasm --target wasm32-wasi --no-run